### ISSUE TITLE
Add ability to add multiple hosts

### ISSUE THREAD

**Issue by JosephWoodward** [justeat/httpclient-interception#115]
**The Problem**

I have some tests that run across multiple environments and I would like to codify that into the test. Initially I've left of the `ForHost` declaration but that introduces potential issues with it running against any service that matches the other builder routes configured.

**Proposed Solution**
I'm just wondering if there's been thought/discussions around adding the following overload to enable you to configure multiple hosts:

```csharp
ForHost(params string[] host)
```

**Alternatives**

One alternative I was considering (which I feel could be a better option) is a regular expression overload as specifying multiple hosts feels a bit inconsistent with the idea of mocking out an HTTP endpoint (as opposed to many, which host implies).

Would be happy to contribute the PR if this is something you feel is valuable outside of my single use case.

**Comment by martincostello** [comment]
This sounds reasonable, it's basically half way between the two current supported ways of _"exactly this"_ and _"anything"_.

I generally err away from `Regex` as it feels a bit heavy-handed a lot of the time. One way to let you do Regular Expressions but not make them the public API would be something like `ForHost(Predicate<string, bool> predicate)` which would allow the caller to provide their own matching (which could then be a call into `Regex.IsMatch()` or something).

I think as long as the new addition is something reasonably flexible that can be built upon for different use-cases then that should be fine. For example, `ForFormContent()` builds on top of `ForContent()`.

Is this something you're chomping at the bit to add, or something you'll do "at some point". The only reason I ask is that if it's soon I'll hold-off on 2.0.2 (to release #108) until this is done too.

**Comment by JosephWoodward** [comment]
A more general purpose`Func<string, bool>` is a good idea. Hoping to have a PR for this in the next few days.

**Comment by martincostello** [comment]
Cool - I'll put this against 2.0.2 then.

**Comment by slang25** [comment]
Probably a separate issue, but what do we think of a general `ForRequest(Predicate<HttpRequest, bool> predicate)` for more advanced scenarios. I don't have a use case at the moment, but I like the idea that I could intercept requests with any arbitrary logic based on the request.

**Comment by martincostello** [comment]
That exists today as [`WithInterceptionCallback(...)`](https://github.com/justeat/httpclient-interception/blob/fe8ae42cee9f94802421ca4ac32279821075aca6/src/HttpClientInterception/HttpRequestInterceptionBuilder.cs#L607-L667), unforunately it's badly named so not as discoverable:

https://github.com/justeat/httpclient-interception/blob/fe8ae42cee9f94802421ca4ac32279821075aca6/tests/HttpClientInterception.Tests/HttpRequestInterceptionBuilderTests.cs#L650-L685

**Comment by slang25** [comment]
Oh nice, didn't know about that. I was hoping you could signal if it was a match or not so that you could still do `.WithContent(...` or whatever.

**Comment by martincostello** [comment]
You can return a `bool` or `Task<bool>` (see the link, not the test), but it's like a _"god mode"_ that overrides everything else, so you can't mix it with the other options.

**Comment by martincostello** [comment]
At least, I think it does. In retrospect it might run at the end as an _"are you sure?"_...

**Comment by slang25** [comment]
Ah, missed the overload 😄 It's good to know it's there if I need it.

**Comment by slang25** [comment]
@martincostello Am I crazy, or does `.For((request) => ...)` do what I want?

**Comment by martincostello** [comment]
@slang25 Yes, you're right. That's the _"god mode"_ I was thinking of.

**Comment by martincostello** [comment]
@JosephWoodward I guess a PR won't be soon so I should look at getting 2.0.2 shipped?

**Comment by JosephWoodward** [comment]
Yeah, I'm sorry but I've still not had a chance to finish it off. It's almost there but I wouldn't want to hold 2.0.2 up.
