### ISSUE TITLE
MissingMethodException when running on mono with newer Newtonsoft.Json

### ISSUE THREAD

**Issue by slang25** [justeat/httpclient-interception#118]
This is quite an exotic setup I know, but this has my tests failing in CI, so I'll be looking into this too.

I have an example here:
https://github.com/justeat/httpclient-interception/commit/a776327d8c1de00e7ad2037e896c171c91c239f6#diff-ad2944e2db1bf6a75b8602f406da7846R13

When running under mono, if I call `.WithJsonContent(...` then it pops with a runtime exception:
```
Error Message:
   System.MissingMethodException : Method not found: JustEat.HttpClientInterception.HttpRequestInterceptionBuilder JustEat.HttpClientInterception.HttpRequestInterceptionBuilderExtensions.WithJsonContent(JustEat.HttpClientInterception.HttpRequestInterceptionBuilder,object,Newtonsoft.Json.JsonSerializerSettings)
```

In recreating this, I discovered that it's not an issue if you are referencing `Newtonsoft.Json` 9.0.1, but if you reference a higher version such as 12.x then this issue pops up.

**Comment by martincostello** [comment]
Yay, breaking changes are fun! 😭

**Comment by martincostello** [comment]
This is particularly weird as we're happily using 12.0.2 internally in our apps' tests.

**Comment by martincostello** [comment]
Though we're _not_ using the overload that takes a `JsonSerializerSettings`.

**Comment by slang25** [comment]
Also, I've not tried it on windows with Full Framework, it might be a mono only quirk, not sure yet.

**Comment by martincostello** [comment]
Actually we are using that overload, it's just that it's an optional parameter:

https://github.com/justeat/httpclient-interception/blob/fe8ae42cee9f94802421ca4ac32279821075aca6/src/HttpClientInterception/HttpRequestInterceptionBuilderExtensions.cs#L213-L217

**Comment by martincostello** [comment]
If this is a blocker it'll have to wait until .NET Core 3.0 ships in September, because then we can ship a 3.0.0 of this as a breaking change and remove the dependency on `Netwonsoft.Json` to give people the option to use `System.Text.Json` instead.

**Comment by slang25** [comment]
I ideally need a fix soonish, my workaround would be running this on core, but we want mono cause it's the closest thing to xamarin iOS/Android which is our target platform.

That exception tells me it can't find `WithJsonContent`, so I don't get why the version of newtonsoft has anything to do with it, surely the exception message is wrong and it means some other method?

**Comment by martincostello** [comment]
Yeah, it's a weird one. Something about optional parameters and/or a change somewhere in 12.x with `JsonSerializerSettings`?

**Comment by martincostello** [comment]
I'd be happy to look at doing a beta of a 3.0.0 with changes to decouple Newtonsoft.Json in the soon-ish future (within a week?) and pushing it to NuGet to unblock you though.

**Comment by slang25** [comment]
That would be amazing, in the meantime if I figure out anything more I'll let you know 😃

**Comment by martincostello** [comment]
I'll see if I can pick up the above this week.

**Comment by martincostello** [comment]
See #127 for a fix candidate.

**Comment by slang25** [comment]
Pulled it down and can confirm this has fixed it 😄 Nice one
