### ISSUE TITLE
Allow access to CancellationToken

### ISSUE THREAD

**Issue by slang25** [justeat/httpclient-interception#142]
The `CancellationToken` that is passed into the delegating handler is flowed into the inner delegating handler which is cool, however it isn't passed into the interception DSL, so there's no way to say in our tests "did the request get aborted".

It would be handy if the `WithInterceptionCallback` gave us that `CancellationToken`, what are your thoughts on this?

**Comment by martincostello** [comment]
Sounds reasonable. If you want to do a PR between now and Monday, this could make it into 3.0.0 which is otherwise ready to go excluding the ceremonies like release notes etc.

**Comment by slang25** [comment]
I've made a start and will try to get it done either today or tomorrow evening.
