### ISSUE TITLE
Question: How to simulate a timeout/no response from downstream service

### ISSUE THREAD

**Issue by dcook-net** [justeat/httpclient-interception#213]
I want to write a test for validating behaviour of a class once it has made a call to  downstream service that is currently down/unavailable (ie, it's never going to process the incoming request)

Am I right in thinking that you would do this as shown in this sample test:

https://github.com/justeat/httpclient-interception/blob/3632d2f3d62ff51e2e3e3119d254d0f6d35ab10f/tests/HttpClientInterception.Tests/Examples.cs#L284

or is there another way?

**Comment by martincostello** [comment]
Hi there - yes, the main way to simulate this use case is to use the `WithInterceptionCallback()` method like so:

https://github.com/justeat/httpclient-interception/blob/3632d2f3d62ff51e2e3e3119d254d0f6d35ab10f/tests/HttpClientInterception.Tests/Examples.cs#L289-L291

**Comment by dcook-net** [comment]
Great - will give this a try.
Thanks for the quick reply
