### ISSUE TITLE
request: more examples for response changing based on how many times called so far

### ISSUE THREAD

**Issue by jamesmanning** [justeat/httpclient-interception#247]
My current situation is that I want to test a Polly policy for handling 429 (too many requests) responses. I'm hoping to be able to have the interceptor return 429 on the first (or maybe the first two) calls, then 200 on the ones after.

**Describe the solution you'd like**
This is probably just a sample to be included

**Describe alternatives you've considered**
I tried keeping a count local var and creating 2 options builders, using WithInterceptionCallback overload passing a Predicate, with one that returned 429 with ++count < 3 then another with count >= 3 that returned 200, but that didn't work (very possible bug on my side and it would have worked fine if I'd done it correctly)

**Additional context**
While there are certainly scopes to change behavior, in this case I need the behavior to change in the context of a single HttpClient.GetAsync call, so AFAICT I can't use scopes to change the behavior in the "middle of the call".  Ideally the sample would maybe include something like an array of objects/tuples of status code and content and as each call came in, it used the next item in the array to determine how to respond.

**Comment by martincostello** [comment]
Thanks for the suggestion James - I've definitely done something _similar_ in our own tests, but I can't remember the specifics.

I'll have a dig and see if I can find one, if not I'll try and rustle something up.

If that fails, I'll have a think about how we could extend the API to support this use case.

**Comment by martincostello** [comment]
Hi James - I've opened #248 with an example of how to achieve this.

It's not the most intuitive with the functionality available today, so definitely highlights an area for improvement!

If this solves your immediate request, I'll merge it and close this issue and open an issue to look at making this use case easier to achieve.

**Comment by jamesmanning** [comment]
That's perfect, thank you! I didn't even look at priority, that makes a lot of sense.

**Comment by martincostello** [comment]
Great, I'm glad it's useful. I'm going to close this now and merge the example, but let us know if you have any other issues.

I've opened #249 to track making this better in a future version.
