### ISSUE TITLE
NullReferenceException when Deregister builder with a custom matcher

### ISSUE THREAD

**Issue by AliKhalili** [justeat/httpclient-interception#361]
Hi Martin,

Deregister a builder from `HttpClientInterceptorOptions` object has not work correctly. This edge case has occurred when a custom matcher was added to a builder and then tried to deregister it from options.

This exception is raised because it should be configured matcher before calling `buildKey` in the `Deregister` method.

Here is a sample scenario for this bug:

```C#
var builder = new HttpRequestInterceptionBuilder()
    .Requests().For(async (request) => await Task.FromResult(true));

var options = new HttpClientInterceptorOptions()
    .Register(builder);

options.Deregister(builder); // NullReferenceException is raised
```

**Comment by martincostello** [comment]
Sorry this took _so long_ to get around to properly investigating and fixing - #454 should fix this bug.
